### ISSUE TITLE
Setup Travis CI

### ISSUE THREAD

**Issue by Jessicashinjo** [code-for-nashville/parcel#21]

**Comment by jordantdavis** [comment]
Acceptance Criteria:
- Setup Travis CI to run backend tests.
- Setup Travis CI to run frontend tests.
- Add instructions on how to run backend tests.
- Add instructions on how to run frontend tests.

**Comment by jordantdavis** [comment]
Also adding build status badge to README and set up branch protection with Travis CI status check requirement.
