### ISSUE TITLE
Wireframe frontend screens

### ISSUE THREAD

**Issue by mshenfield** [code-for-nashville/parcel#6]
@enlore has actually already done this!  Making an issue for documentation and 🙌 .  This application is being re-purposed.  It started life as a way to lookup the _set backs_ for a particular address.  Based on a request from the Planning department, we're now using it as a way to lookup _acceptable use_ for a particular address.

Both answer zoning questions ("how many feet do structures need to be from the edge of my property?" vs "what kind of structures and business am I allowed to build on my property?").

![img_0484](https://user-images.githubusercontent.com/4812055/28250945-65ad737e-6a39-11e7-9f85-09d413dc57f9.JPG)
![img_0485](https://user-images.githubusercontent.com/4812055/28250946-65ad7e0a-6a39-11e7-8b5b-25606c05dfd2.JPG)

Screen 1: The home screen. It includes "Branding" (logo, etc.), a brief blurb, and two search boxes. Search box 1 is an address input, search box 2 is a dropdown which allows the user to select a "Use Category", e.g. "Residential Uses", "Institutional Uses", etc. This also includes a footer.

Screen 2: Search result screen. After the user has clicked "Submit", they are taken to a view with the search input towards the top of the screen. Below, a list of results (format TBD), which at least include the zone code ("AG", "RS80") with a brief description, and then a list of "uses" for that use category, e.g. "Single-Family": "Permitted".

Screen 3: A user can change the inputs in the two search, click submit, and view a new set of results.

**Comment by enlore** [comment]
Updated versions of my lo-lo-lo-fi wireframes: https://sketch.cloud/s/522Vx/p/mobile-screens
