### ISSUE TITLE
First draft of frontend

### ISSUE THREAD

**Issue by mshenfield** [code-for-nashville/parcel#7]
Based on the wireframes in #6, create a first draft of the frontend for the usage lookup page.

**Comment by mshenfield** [comment]
CC: @jessicashinjo

**Comment by Jessicashinjo** [comment]
![parcelscreenshot1](https://user-images.githubusercontent.com/10501794/29697795-e33f8a92-8916-11e7-9461-345b0c438bab.png)
![parcelscreenshot2](https://user-images.githubusercontent.com/10501794/29697796-e3429caa-8916-11e7-9eee-6d4f2ee66c11.png)

**Comment by Jessicashinjo** [comment]
First Design Draft done by Greg Wiley
